# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dca8a261f54d8f23c1a99ed299f52dd4baefb8a4e564ad9c94df114d7088dcdabbc8c53cb761af18f470cb0a12346af87c041f6110ee736de59116e5be41d37f

test:
  secret_key_base: 684d8caa4542fe5106be69d6313f7d4c7d088b1e4feec7ece7cee3a304664d54e10fc9fe0238da854cfddf170857c9e512528834de5e5994a1622b152463834f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
